# Sample YAML file to validate and export an ARM template into a build artifact
# Requires a package.json file located in the target repository

trigger:
- master

pool:
  vmImage: 'windows-latest'

# variables:
#   - group: DataOpsUAT
  
steps:

- powershell: dir $(Build.SourcesDirectory) -recurse

- task: UsePythonVersion@0
  displayName: Configuring Python Version
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'


- powershell: |
    pip3 install --upgrade databricks-cli
    
    $args = @"
    $(databricks.host)

    $(databricks.token)

    "@

    Write-Output $args

    Write-Output $args | & databricks configure --token 

    Write-Output "`nDatabricks workspace list:"
    & databricks workspace list
    
    

  displayName: Configure databricks
- bash: |
    databricks workspace list --profile AZDO
    databricks workspace import_dir -o --profile AZDO $(Build.SourcesDirectory)/databricks/ /demo
